# Travis CI for hello-bazel
#
# Author: Fangjun Kuang, fangjun.kuang <at> gmail <dot> com
# Date: December 16, 2018
#

os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - PATH=$HOME/bin:$HOME/software/linaro/bin:$HOME/software/qemu/bin:${PATH}
    - LD_LIBRARY_PATH=$HOME/software/linaro/aarch64-linux-gnu/libc/lib:${LD_LIBRARY_PATH}

notifications:
  email: false

sudo: false

install:
    - ./travis/install-bazel.sh "$TRAVIS_OS_NAME"
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./travis/install-toolchain.sh; fi

script:
    - ./travis/scripts.sh "$TRAVIS_OS_NAME"

