py_library(
    name = "person",
    srcs = ["person.py"],
)

py_test(
    name = "person_test",
    srcs = ["person_test.py"],
    deps = [":person"],
)

py_library(
    name = "tools",
    srcs = ["tools.py"],
)

py_test(
    name = "tools_test",
    srcs = ["tools_test.py"],
    deps = [":tools"],
)
